### ISSUE TITLE
Add config modif for localization

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-docs#136]
You probably forgot but when you want install Polyglot you need to modify the /client/config.coffee and add: 
```
  plugins:
        jade:
            globals: ['t']

  files: ...
```
In my case, the tuto dont work and add this have resolve my issue.
